### ISSUE TITLE
eo-dtx

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/ideas#3]
Transactional component for distributed transactions and saga

**Comment by h1alexbel** [comment]
can be started after https://github.com/eo-cqrs/eo-kafka/issues/4

**Comment by h1alexbel** [comment]
i have an idea how to simplify tx-management:
instead saga pattern we can have something like this:

```
server-0 init tx: ${data}
server-1: connected
server-1: ok
server-2: connected
server-2: failed!
transaction rollbacked
```
I call it dashboard of distributed transactions.
So, some service can be tx initiator. Others can respond ```ok``` or ```failed```

cc:
@l3r8yJ

**Comment by l3r8yJ** [comment]
@h1alexbel looks interesting, I need to dive into the rollback mechanism

**Comment by h1alexbel** [comment]
for now, I don't have a clear understanding of how to simplify distributed transactions, for now we can do #22 and #4
