### ISSUE TITLE
eo-qce

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/ideas#4]
the component that can do ```event``` wrapping around the original object

**Comment by h1alexbel** [comment]
@l3r8yJ 
There is a formal idea about how to translate an event into an object and vice versa

```Event``` -> ```Domain Object```
```Domain Object``` -> ```Event```

```java
interface Event {
String content();
}
```

```java
class XmlEvent {

}
```

```java
class JsonEvent {
}
```

```java
class User implements DomainObject {}
...
DomainObject user = new User();
Event event =  new Event.Envelope(user);
```

I would like to pick proper naming for ```Event``` and ```DomainObject```

**Comment by h1alexbel** [comment]
maybe its should be smth like this:

```java
interface Query {
Outcome outcome(); // can be <X> or some Outcome
}

interface Command {
Event eventize(); // preparing event particular command
}

interface Event {
String veil(); // or content()
}

new GetUserByIdQuery()

new CreateUserCommand() -> new CreateUserEvent()
```

cc:
@l3r8yJ

**Comment by h1alexbel** [comment]
qce stands for Query Command Event

**Comment by h1alexbel** [comment]
and right now I belive thats a base stuff we need to implement

**Comment by l3r8yJ** [comment]
@h1alexbel i suggest something like [that](https://github.com/l3r8yJ/elegram-api/blob/master/src/main/java/ru/elegramapi/www/request/TRqEnvelope.java)
```java
abstract class EventEnvelope implements Event {
    // bunch of ctors 
}
```
what do you think?

**Comment by h1alexbel** [comment]
@l3r8yJ yes, we can go with this, but why we need all this ctors?

**Comment by h1alexbel** [comment]
@l3r8yJ I've created a repo. [here](https://github.com/eo-cqrs/eo-qce) it is
