### ISSUE TITLE
eo-esql

### ISSUE THREAD

**Issue by h1alexbel** [eo-cqrs/ideas#7]
SQL + eo-event = Event SQL

as SQL we can use [jcabi-jdbc](https://github.com/jcabi/jcabi-jdbc), or develop custom eo-postgres/eo-sql on top of that.

**Comment by h1alexbel** [comment]
what do you think @l3r8yJ ?

**Comment by h1alexbel** [comment]
can be used with jooq

**Comment by l3r8yJ** [comment]
@h1alexbel I think it's a good idea, but I suggest just writing down ideas for other projects until the `1.0.0` release of `eo-kafka`. I think we should focus our energies on it for now, what do you think?

**Comment by l3r8yJ** [comment]
@h1alexbel we can also post links to other projects that we are going to wrap in the issue of ideas

**Comment by h1alexbel** [comment]
@l3r8yJ yeah, I totally agree with you. I'm using this repo and its issue like note for the future ideas
