### ISSUE TITLE
new logo

### ISSUE THREAD

**Issue by l3r8yJ** [eo-cqrs/ideas#8]
the logo for the whole eo-cqrs, @h1alexbel what do you think it should look like? can you describe it?

**Comment by h1alexbel** [comment]
@l3r8yJ maybe new logo is combination of events, segration of them(CQRS) and old plain cactoos)

**Comment by l3r8yJ** [comment]
@h1alexbel so far, I have no idea how I can't portray the sources of events

**Comment by h1alexbel** [comment]
@l3r8yJ 
Look, I have an idea:
UMLish segregation of arrows;
Events can be presented as ```{}```

**Comment by h1alexbel** [comment]
new logo is here. @l3r8yJ thanks!
